usdcat ./SubUSDs/DroneCircuitBoard.usd > ./test_usd_files/Drone/DroneCircuitBoard.usda
usdcat ./SubUSDs/DroneCircuitBoard_Mock.usd > ./test_usd_files/Drone/DroneCircuitBoard_Mock.usda
usdcat ./SubUSDs/DronePayloadBracket.usd > ./test_usd_files/Drone/DronePayloadBracket.usda
usdcat ./SubUSDs/Drone_Complete.usd > ./test_usd_files/Drone/Drone_Complete.usda
usdcat ./SubUSDs/Drone_Large_Complete.usd > ./test_usd_files/Drone/Drone_Large_Complete.usda
usdcat ./SubUSDs/Drone_Minimal.usd > ./test_usd_files/Drone/Drone_Minimal.usda
usdcat ./SubUSDs/Payload_Camera.usd > ./test_usd_files/Drone/Payload_Camera.usda
usdcat ./SubUSDs/Payload_Camera_Mock.usd > ./test_usd_files/Drone/Payload_Camera_Mock.usda
usdcat ./SubUSDs/Payload_Radar.usd > ./test_usd_files/Drone/Payload_Radar.usda
usdcat ./SubUSDs/Payload_Radar_Mock.usd > ./test_usd_files/Drone/Payload_Radar_Mock.usda
